### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by siva-u** [DLance96/event-ticker#2]
http://prnt.sc/by97rx - Doesn’t check date and only check times meaning you can only schedule things for the day.

**Comment by DLance96** [comment]
Hmmmm I think it something with your setup. I have that working when I test it. But I will look into it.

https://gyazo.com/2f7f8c2afec8322ab929b900dc1b7205

**Comment by siva-u** [comment]
Seems as if it has fixed on my end http://prntscr.com/bybm6f
