### ISSUE TITLE
[Help Wanted] Accessing the SQLite file

### ISSUE THREAD

**Issue by siva-u** [DLance96/event-ticker#7]
Is there a way for me to access the SQLite file so that I can see who hosted when and a record of all the games?

**Comment by DLance96** [comment]
http://sqlitebrowser.org/

**Comment by DLance96** [comment]
You should be able to pull the file off the server and use the above program to read through it like any other SQL.

Am I good to close this?

**Comment by siva-u** [comment]
Thanks,

closed
